sudo: required

language: minimal

services:
  - docker

before_install:
  - docker build -t nelsonr/docker-react -f Dockerfile.dev .

script:
    - docker run nelsonr/docker-react npm run test -- --coverage