sudo: required

language: ruby
install:
  - gem uninstall bundler
  - gem install bundler --version '1.7.4'

services:
  - docker

before_install:
  - docker build -t nelsonr/docker-react -f Dockerfile.dev .

script:
  - gem install bundler
  - docker run nelsonr/docker-react npm run test -- --coverage