sudo: required

services:
  - docker

before_install:
  - docker build -t nelsonr/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true nelsonr/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  edge: true
  app: "docker-react2"
  env: "Dockerreact1-env"
  bucket_name: "elasticbeanstalk-ap-south-1-353594477466"
  bucket_path: "docker-react2"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
